[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "SiphonServer"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "anthropic>=0.64.0",
    "chain>=1.0",
    "database-clients",
    "fastapi>=0.116.1",
    "google-genai>=1.32.0",
    "instructor>=1.10.0",
    "jinja2>=3.1.6",
    "ollama>=0.5.3",
    "openai>=1.99.9",
    "pillow>=11.3.0",
    "psycopg2-binary>=2.9.10",
    "pydantic>=2.11.7",
    "pytest>=8.4.1",
    "python-dotenv>=1.1.1",
    "rich>=14.1.0",
    "siphon>=0.10.0",
    "tiktoken>=0.11.0",
    "tinydb>=4.8.2",
    "uvicorn>=0.35.0",
]

[tool.hatch.build.targets.wheel]
include = ["*"]

[tool.uv.sources]
siphon = { path = "../Siphon" }
chain = { path = "../Chain" }
database-clients = { path = "../database-clients" }
